### ISSUE TITLE
error loading model in editor and IOException when uploading specification

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#135]
```
What steps will reproduce the problem?
1. convert old yawl files to version 2.0 with the converter
2. load the converted file into the editor
3. produce an xml file and upload in the engine.

I just installed update 2 of of yawl beta 2.0.

My yawl files have originally been made in version 1.4.4 of the editor and 
saved in version 1.4.5 of the editor. 

I have converted the ywl files to the 2.0 version with the conversion tool 
that has been provided on the forum (no error messages during conversion, 
for example, for gynOncEnglish9.ywl, the following is reported: Loading 
file: gynOncEnglish9.ywl
Converting package names.
Saving file:gynOncEnglish9.ywl_v2.0). 

Afterwards, I loaded the files into the editor (the one going together 
with update 2) and generate an xml file for them. Unfortunately, when 
loading the file in the editor, error messages are shown. Subsequently, 
when generating an xml file with the editor and uploading this in the 
engine an IOException is shown. For example, for file gynonc.xml, the 
following error message is shown: IOException uploading specification 
gynonc.xml
Moreover, for file lab.xml the same happens.

Nevertheless, in the editor I could define a new yawl model, which could 
be successfully uploaded in the engine and executed.

For running the editor, I used the following java version (command java-
version):
java version "1.6.0_03"
Java(TM) SE Runtime Environment (build 1.6.0_03-b05)
Java HotSpot(TM) Client VM (build 1.6.0_03-b05, mixed mode, sharing)

I include several files.
gynOncEnglish9.ywl (file made in editor 1.4.4, saved in 1.4.5 and worked 
in yawl 8.2)
lab.ywl (same as for gynOncEnglish9.ywl)
gynOncEnglish9_ywl_v2.0.ywl (the yawl 2.0 version)
lab_ywl_v2.0.ywl (the yawl 2.0 version)
gynonc.xml (xml version of gynOncEnglish9_ywl_v2.0.ywl)
lab.xml (xml version of lab_ywl_v2.0.ywl)

When loading gynOncEnglish9.ywl, the following error message is shown. (I 
cannot give the complete one, as this is not shown in the dos screen)

ERROR MESSAGE:
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
org.xml.sax.SAXParseException: Content is not allowed in trailing section.
        at 
org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Un
known Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown 
Source)

        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown 
Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown 
Source)
        at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown 
Source)
        at 
org.apache.xerces.impl.XMLDocumentScannerImpl$TrailingMiscDispatcher.
dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)



 
```

Original issue reported on code.google.com by `Ronny.M...@gmail.com` on 5 Sep 2008 at 9:00

Attachments:
* [gynOncEnglish9.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-0/gynOncEnglish9.ywl)
* [gynOncEnglish9_ywl_v2.0.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-0/gynOncEnglish9_ywl_v2.0.ywl)
* [lab.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-0/lab.ywl)
* [lab_ywl_v2.0.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-0/lab_ywl_v2.0.ywl)
* [gynonc.xml](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-0/gynonc.xml)
* [lab.xml](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-0/lab.xml)

**Comment by yawlfoundation** [comment]
```
Hi Ronny,

The errors produced by the 2.0 editor when opening a converted ywl file are
incidental and can be ignored - no data is lost in the process. I confirmed 
this by
opening the 1.5 version files in a 1.5 editor and comparing to the 2.0 files in 
the
2.0 editor.

Also, I am able to successfully upload and run in the engine the xml files you
generated, so that problem seems to be a local one. I have modifed the
resourceService.war file to generate the error to the log file. Please download 
it
from https://fileshare.qut.edu.au/public/adamsmj/resourceService.war and 
replace your
current version with this one. Then try to load the xml and post here the error
generated to the log file.

Thanks, Michael.
```

Original comment by `yawl.mic...@gmail.com` on 8 Sep 2008 at 2:06

**Comment by yawlfoundation** [comment]
Original comment by `yawl.mic...@gmail.com` on 8 Sep 2008 at 2:06
* Changed state: **UnderObservation**

**Comment by yawlfoundation** [comment]
```
Hi Michael,

thank you for the feedback. Here is the log of the resourceService when I run 
lab.xml.

Moreover, when I fill in http://localhost:8080/yawl/ia/upload as address in 
Firefox 
then the following is shown:
<response>
	<failure>
<reason>Invalid action or exception was thrown.</reason>
</failure>
</response>

Hope this helps. 

Best regards,

Ronny



```

Original comment by `Ronny.M...@gmail.com` on 9 Sep 2008 at 10:02

Attachments:
* [yawl_resourceService.log](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-3/yawl_resourceService.log)

**Comment by yawlfoundation** [comment]
```
Hi Ronny,

I have traced the issue to a bug in the YAWL4Study installer. An update will be
available soon.

Cheers, Michael.
```

Original comment by `yawl.mic...@gmail.com` on 12 Sep 2008 at 12:56

**Comment by yawlfoundation** [comment]
```
Hi Michael,

To be honest, I installed yawl4enterprise. Is to bug also related to this one?

Cheers,

Ronny

```

Original comment by `Ronny.M...@gmail.com` on 12 Sep 2008 at 8:58

**Comment by yawlfoundation** [comment]
```
Hi Ronny,

Oh..., well, in that case ;-)

No, that's a different bug. What OS are you running on? In any case, download 
the
latest build from: https://fileshare.qut.edu.au/public/adamsmj/yawl.war and 
replace
your current yawl.war with this one. Let me know if it fixes the problem.
```

Original comment by `yawl.mic...@gmail.com` on 15 Sep 2008 at 9:10

**Comment by yawlfoundation** [comment]
```
Hi Michael,

Sorry for not returning to you back earlier. Last week I was on holiday and not 
connected to the internet.

What I did is the following. I installed yawl4enterprise and yawl4student 
according 
by using the installers provided by Stephan Clemens in his mail from 15-9-2008. 
Afterwards, I replaces the yawl.war in the webapps folder by the one from 
https://fileshare.qut.edu.au/public/adamsmj/yawl.war.

If I upload gynonc.xml in yawl4enterprise, I get an IOexception (probably 
similar to 
the one I got before). I attach the yawl_resourceService.log to this comment.

If I upload gynonc.xml in yawl4study, I only get the error that the timeservice 
is 
not registered. I saved this one in yawlStudentException.txt. However, I have 
the 
idea that this does not harm anything as I can successfully start a case here. 
Moreover, I can perform workitems. This looks good!

However, I saw one small issue. If I do something on the tab 'work queues', 
e.g., I 
start a workitem via the offered subtap, and I click afterwards on Admin 
Queues, 
then I get a screen with white backgroup and text on which the buttons are 
missing. 
I made a screenshot of this (whitescreen.bmp). If I would click now on the 
Worklisted subtab, then I get the screen with blue background including 
buttons. Is 
this issue known to you? (A similar issues happens for the other way around.)

By the way, as OS I have windows server 2003. If you think this might give 
problems, 
I can also try to run everything under windows xp with my desktop at the TU/e.

Cheers,

Ronny

```

Original comment by `Ronny.M...@gmail.com` on 22 Sep 2008 at 7:18

Attachments:
* [yawl_resourceService.log](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-7/yawl_resourceService.log)
* [yawlStudentException.txt](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-7/yawlStudentException.txt)
* [whitescreen.bmp](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-7/whitescreen.bmp)
* [](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-7/)

**Comment by yawlfoundation** [comment]
```
[deleted comment]
```

**Comment by yawlfoundation** [comment]
```
Hello Michael,

Recently, I was again playing with yawl4study and yawl4enterprise in order to 
generate pictures for the yawl book. 
When I upload the gynonc.xml file and start a case, I get an error which is 
saved in 
error.htm.
Strange is that I get this error now for both yawl4study and yawl4enterprise, 
where 
it first seemed that something was working for yawl4study. I downloaded both 
yawl4study and yawl4enterprise at september 21. 

Do you have any clue what is wrong?

Best regards,

Ronny

```

Original comment by `Ronny.M...@gmail.com` on 29 Sep 2008 at 4:13

Attachments:
* [ERROR.htm](https://storage.googleapis.com/google-code-attachments/yawl/issue-135/comment-9/ERROR.htm)

**Comment by yawlfoundation** [comment]
```
Hi Ronny,

The latest build on fileshare (link is in the last YAWLTesters email) fixes all 
the
problems listed above.

Since this issue has 'morphed' from the original issue, I'll close this one. If
there's any further issues, it's best to open a new issue for it.

Cheers, Michael.
```

Original comment by `yawl.mic...@gmail.com` on 2 Oct 2008 at 11:33
* Changed state: **Fixed**
