### ISSUE TITLE
editor put in faulty state

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#136]
```
What steps will reproduce the problem?
1. Load lab.yawl (made with version 1.4.4 of the editor and saved in 
version 1.4.5 of the editor)
2. Click on ok button of the messagebox which informs that this file can 
not loaded (which is logically as this one is made with an old editor).
3. Load test.ywl. This one has been made in version 2.0 update 2 of the 
editor and works well. The model is shown. However, options in the editor 
which are shown when successfully opening a file are not shown now. For 
example, I can not export to an xml file.

As java version I'm using:
java version "1.6.0_03"
Java(TM) SE Runtime Environment (build 1.6.0_03-b05)
Java HotSpot(TM) Client VM (build 1.6.0_03-b05, mixed mode, sharing)

Actually, I found this one when I incidently clicked on the wrong file and 
then opened the correct one.

The error message what I get when opening lab.ywl is:
        at com.sun.beans.ObjectHandler.eval(Unknown Source)
        at com.sun.beans.ObjectHandler.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement
(Unknown Sour
ce)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElemen
t(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException: target should not be null
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException: target should not be null
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.eval(Unknown Source)
        at com.sun.beans.ObjectHandler.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement
(Unknown Sour
ce)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElemen
t(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException: target should not be null
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException: target should not be null
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.eval(Unknown Source)
        at com.sun.beans.ObjectHandler.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement
(Unknown Sour
ce)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElemen
t(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException: target should not be null
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException: target should not be null
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException: target should not be null
        at java.beans.Statement.invoke(Unknown Source)
        at java.beans.Expression.getValue(Unknown Source)
        at com.sun.beans.MutableExpression.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.getValue(Unknown Source)
        at com.sun.beans.ObjectHandler.endElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown 
Source
)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(
Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContent
Dispatcher.dispatch(Unknown Source)
        at 
org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Un
known Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown 
Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown 
Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse
(Unknown Sour
ce)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at java.beans.XMLDecoder.getHandler(Unknown Source)
        at java.beans.XMLDecoder.readObject(Unknown Source)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:444)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)
java.lang.NullPointerException
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.readSpecification(SpecificationArchiveHandler.java:446)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.openSpecificationFromFile(SpecificationArchiveHandler.java:426)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:389)
        at 
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHand
ler.processOpenRequest(SpecificationArchiveHandler.java:345)
        at 
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processR
equestState(ArchivingThread.java:140)
        at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run
(Arch
ivingThread.java:113)



 
```

Original issue reported on code.google.com by `Ronny.M...@gmail.com` on 5 Sep 2008 at 9:14

Attachments:
* [lab.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-136/comment-0/lab.ywl)
* [test.ywl](https://storage.googleapis.com/google-code-attachments/yawl/issue-136/comment-0/test.ywl)

**Comment by yawlfoundation** [comment]
```
Fixed for next editor release.
```

Original comment by `yawl.mic...@gmail.com` on 8 Sep 2008 at 2:49
* Changed state: **Fixed**
