### ISSUE TITLE
Dynamic form generation fails

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#256]
```
What steps will reproduce the problem?
1. load attached orderfulfilment files
2. launch a case
3. try to view/edit the first task

Error message on screen
Cannot view task contents - problem initialising dynamic form from task
specification. Please see the log files for details.

This error occurs only when using the latest war files. Does not happen
with update3.

Error message in log
2009-02-10 11:59:29,464 [INFO ] ResourceMap          :- Resourcing
specification parse completed for task: Create_Purchase_Order_104
2009-02-10 11:59:38,087 [INFO ] ResourceMap          :- Resourcing
specification parse completed for task: Create_Purchase_Order_104
2009-02-10 11:59:47,435 [INFO ] ResourceManager      :-    checkout
successful: 2.1:Create_Purchase_Order_104
2009-02-10 11:59:49,746 [ERROR] ResourceManager      :- Could not retrieve
schema for workitem parameters
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:165)
	at
org.yawlfoundation.yawl.engine.interfce.Interface_Client.getReply(Interface_Clie
nt.java:201)
	at
org.yawlfoundation.yawl.engine.interfce.Interface_Client.send(Interface_Client.j
ava:127)
	at
org.yawlfoundation.yawl.engine.interfce.Interface_Client.executeGet(Interface_Cl
ient.java:58)
	at
org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedCl
ient.getSpecification(InterfaceB_EnvironmentBasedClient.java:173)
	at
org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceBWebsideController.g
etSpecificationData(InterfaceBWebsideController.java:449)
	at
org.yawlfoundation.yawl.resourcing.ResourceManager.getSpecData(ResourceManager.j
ava:2475)
	at
org.yawlfoundation.yawl.resourcing.ResourceManager.getDataSchema(ResourceManager
.java:2773)
	at
org.yawlfoundation.yawl.resourcing.jsf.SessionBean.getTaskSchema(SessionBean.jav
a:724)
	at
org.yawlfoundation.yawl.resourcing.jsf.dynform.DynFormFactory.getSchema(DynFormF
actory.java:208)
	at
org.yawlfoundation.yawl.resourcing.jsf.dynform.DynFormFactory.initDynForm(DynFor
mFactory.java:185)
	at
org.yawlfoundation.yawl.resourcing.jsf.userWorkQueues.btnView_action(userWorkQue
ues.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.sun.faces.el.MethodBindingImpl.invoke(MethodBindingImpl.java:126)
	at
com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.ja
va:72)
	at
com.sun.rave.web.ui.appbase.faces.ActionListenerImpl.processAction(ActionListene
rImpl.java:57)
	at javax.faces.component.UICommand.broadcast(UICommand.java:312)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:267)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:381)
	at
com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.ja
va:75)
	at com.sun.faces.lifecycle.LifecycleImpl.phase(LifecycleImpl.java:221)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:90)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:197)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at com.sun.rave.web.ui.util.UploadFilter.doFilter(UploadFilter.java:194)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at
org.yawlfoundation.yawl.resourcing.jsf.SessionTimeoutFilter.doFilter(SessionTime
outFilter.java:61)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at org.yawlfoundation.yawl.util.CharsetFilter.doFilter(CharsetFilter.java:34)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
33)
	at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
91)
	at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
	at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109
)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:845)
	at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Pr
otocol.java:583)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
	at java.lang.Thread.run(Thread.java:619)
2009-02-10 12:03:48,903 [ERROR] ResourceManager      :- Could not retrieve
schema for workitem parameters
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:165)
	at
org.yawlfoundation.yawl.engine.interfce.Interface_Client.getReply(Interface_Clie
nt.java:201)
	at
org.yawlfoundation.yawl.engine.interfce.Interface_Client.send(Interface_Client.j
ava:127)
	at
org.yawlfoundation.yawl.engine.interfce.Interface_Client.executeGet(Interface_Cl
ient.java:58)
	at
org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EnvironmentBasedCl
ient.getSpecification(InterfaceB_EnvironmentBasedClient.java:173)
	at
org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceBWebsideController.g
etSpecificationData(InterfaceBWebsideController.java:449)
	at
org.yawlfoundation.yawl.resourcing.ResourceManager.getSpecData(ResourceManager.j
ava:2475)
	at
org.yawlfoundation.yawl.resourcing.ResourceManager.getDataSchema(ResourceManager
.java:2773)
	at
org.yawlfoundation.yawl.resourcing.jsf.SessionBean.getTaskSchema(SessionBean.jav
a:724)
	at
org.yawlfoundation.yawl.resourcing.jsf.dynform.DynFormFactory.getSchema(DynFormF
actory.java:208)
	at
org.yawlfoundation.yawl.resourcing.jsf.dynform.DynFormFactory.initDynForm(DynFor
mFactory.java:185)
	at
org.yawlfoundation.yawl.resourcing.jsf.userWorkQueues.btnView_action(userWorkQue
ues.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.sun.faces.el.MethodBindingImpl.invoke(MethodBindingImpl.java:126)
	at
com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.ja
va:72)
	at
com.sun.rave.web.ui.appbase.faces.ActionListenerImpl.processAction(ActionListene
rImpl.java:57)
	at javax.faces.component.UICommand.broadcast(UICommand.java:312)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:267)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:381)
	at
com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.ja
va:75)
	at com.sun.faces.lifecycle.LifecycleImpl.phase(LifecycleImpl.java:221)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:90)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:197)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:290)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at com.sun.rave.web.ui.util.UploadFilter.doFilter(UploadFilter.java:194)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at
org.yawlfoundation.yawl.resourcing.jsf.SessionTimeoutFilter.doFilter(SessionTime
outFilter.java:61)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at org.yawlfoundation.yawl.util.CharsetFilter.doFilter(CharsetFilter.java:34)
	at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilt
erChain.java:235)
	at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.
java:206)
	at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:2
33)
	at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:1
91)
	at
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
	at
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109
)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:845)
	at
org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Pr
otocol.java:583)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
	at java.lang.Thread.run(Thread.java:619)

```

Original issue reported on code.google.com by `stephan....@googlemail.com` on 10 Feb 2009 at 2:07

Attachments:
* [orderfulfilment.yawl](https://storage.googleapis.com/google-code-attachments/yawl/issue-256/comment-0/orderfulfilment.yawl)
* [orderfulfilment.ybkp](https://storage.googleapis.com/google-code-attachments/yawl/issue-256/comment-0/orderfulfilment.ybkp)

**Comment by yawlfoundation** [comment]
```
This was fixed a while ago, but the latest build list has not been updated with 
the
change. A new build will be available within the next 24 hours.
```

Original comment by `yawl.mic...@gmail.com` on 13 Feb 2009 at 12:17
* Changed state: **Fixed**
