### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#290]
```
This error occurs randomly
Exception in thread "Thread-8" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuffer.append(Unknown Source)
	at org.yawlfoundation.yawl.unmarshal.YMarshal.marshal(YMarshal.java:131)
	at org.yawlfoundation.yawl.unmarshal.YMarshal.marshal(YMarshal.java:147)
	at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.get
EngineSpecificationXML(EngineSpecificationExporter.java:183)
	at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.get
AndCheckEngineSpecificationXML(EngineSpecificationExporter.java:170)
	at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.che
ckAndExportEngineSpecToFile(EngineSpecificationExporter.java:84)
	at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.save
SpecificationToFile(EngineSpecificationHandler.java:170)
	at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.engi
neFormatFileExport(EngineSpecificationHandler.java:87)
	at
org.yawlfoundation.yawl.editor.thirdparty.engine.AvailableEngineProxyImplementat
ion.engineFormatFileExport(AvailableEngineProxyImplementation.java:74)
	at
org.yawlfoundation.yawl.editor.thirdparty.engine.YAWLEngineProxy.engineFormatFil
eExport(YAWLEngineProxy.java:95)
	at
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.saveUpd
atingGUI(SpecificationArchiveHandler.java:223)
	at
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.saveUpd
atingGUI(SpecificationArchiveHandler.java:205)
	at
org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.process
SaveRequest(SpecificationArchiveHandler.java:102)
	at
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processRequestState
(ArchivingThread.java:134)
	at
org.yawlfoundation.yawl.editor.specification.ArchivingThread.run(ArchivingThread
.java:115)

```

Original issue reported on code.google.com by `stephan....@googlemail.com` on 1 Mar 2009 at 11:11

**Comment by yawlfoundation** [comment]
```
memory leak found and fixed for next editor build
```

Original comment by `yawl.mic...@gmail.com` on 6 Mar 2009 at 8:16
* Changed state: **Fixed**
