### ISSUE TITLE
Use of < symbol in Editor notes causes data corruption in Editor save file

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#319]
```
What steps will reproduce the problem?
1. Create a new specification in the Editor
2. Add in a new Atomic Tasks and add a "note" to it contained a "<" symbol
3. Save the specification (note: Stack Trace occurs but GUI reports nothing)
4. Attempt to re-open the save file - ERROR

What is the expected output? What do you see instead?
A re-opened specification design.

What version of the product are you using? On what operating system?
YAWL2 RC1 / Linux (Ubuntu 8.04 Hardy)

Please provide any additional information below.
Should the data be either encoded or CDATA used?

```

Original issue reported on code.google.com by `andrew.h...@first-utility.com` on 25 Mar 2009 at 6:03

**Comment by yawlfoundation** [comment]
```
Here's the stack trace thrown at the point of saving the spec:

2009-03-25 16:25:59,989 [ERROR] :- Error unmarshalling specification from XML.
org.jdom.input.JDOMParseException: Error on line 1: Content is not allowed in 
prolog.
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:504)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:888)
        at
org.yawlfoundation.yawl.unmarshal.YMarshal.unmarshalSpecifications(YMarshal.java
:77)
        at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationImporter.imp
ortEngineSpecificationAsEngineObjects(EngineSpecificationImporter.java:120)
        at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationImporter.imp
ortEngineSpecificationFromFile(EngineSpecificationImporter.java:78)
        at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.impo
rtEngineSpecificationFile(EngineSpecificationHandler.java:104)
        at
org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.engi
neFormatFileImport(EngineSpecificationHandler.java:95)
        at
org.yawlfoundation.yawl.editor.thirdparty.engine.AvailableEngineProxyImplementat
ion.engineFormatFileImport(AvailableEngineProxyImplementation.java:82)
        at
org.yawlfoundation.yawl.editor.thirdparty.engine.YAWLEngineProxy.engineFormatFil
eImport(YAWLEngineProxy.java:103)
        at
org.yawlfoundation.yawl.editor.specification.ArchivingThread.processRequestState
(ArchivingThread.java:146)
        at
org.yawlfoundation.yawl.editor.specification.ArchivingThread.run(ArchivingThread
.java:115)

```

Original comment by `andrew.h...@first-utility.com` on 25 Mar 2009 at 6:09

**Comment by yawlfoundation** [comment]
```
fixed - notes are now encoded on save and decoded on open
```

Original comment by `yawl.mic...@gmail.com` on 26 Mar 2009 at 9:54
* Changed state: **Fixed**
