### ISSUE TITLE
Can't login to Resource Service with admin login

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#414]
```
What steps will reproduce the problem?
1. Install YAWL4Study-2.1.
2. Run the StartEngine binary.
3. Run the ControlCenter binary.
4. Try to log in with user "admin" and pass "YAWL" (without commas).

What is the expected output? What do you see instead?
Expected output: The Resource Service Page
What I see: the error message: "Missing or invalid organisational data source. 
The resource service requires a connection to a valid data source that contains 
organisational data. Please check the settings in the service's web.xml to 
ensure a valid data source is set."

What version of the product are you using? YAWL4Study-2.1
On what operating system? MacOSX


Please provide any additional information below.
The log from the Resource Service:
2011-02-06 19:31:26,332 [INFO ] ResourceManager      :- Loading org data...
2011-02-06 19:31:26,434 [ERROR] HibernateEngine      :- Caught Exception: 
Couldn't connect to datasource - starting with an empty dataset
2011-02-06 19:31:26,435 [ERROR] ResourceGateway      :- Gateway Initialisation 
Exception
java.lang.NullPointerException
	at org.yawlfoundation.yawl.resourcing.datastore.orgdata.HibernateImpl.loadResources(HibernateImpl.java:116)
	at org.yawlfoundation.yawl.resourcing.ResourceManager.loadResources(ResourceManager.java:646)
	at org.yawlfoundation.yawl.resourcing.ResourceManager.initOrgDataSource(ResourceManager.java:207)
	at org.yawlfoundation.yawl.resourcing.rsInterface.ResourceGateway.init(ResourceGateway.java:86)
	at javax.servlet.GenericServlet.init(GenericServlet.java:256)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1172)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:992)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4058)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4371)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:525)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:926)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:889)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:492)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1149)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:311)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:719)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:443)
	at org.apache.catalina.core.StandardService.start(StandardService.java:516)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:578)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:288)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:413)
2011-02-06 19:31:49,818 [WARN ] SessionTimeoutFilter :- User session has expired


```

Original issue reported on code.google.com by `bernardoopinto@gmail.com` on 6 Feb 2011 at 8:02

**Comment by yawlfoundation** [comment]
```
It appears the Derby database has not installed correctly, or is not running. 
Perhaps the install did not successfully complete. Please uninstall/reinstall. 
If that doesn't correct he problem, please report the OSX and Java versions 
being used, thanks. 
```

Original comment by `yawl.mic...@gmail.com` on 7 Feb 2011 at 11:58
* Changed state: **UnderObservation**

**Comment by yawlfoundation** [comment]
```
I saw more the default.log file and there was no database connection indeed.
Reinstalled and chose the Java installation from /usb/bin. Problem solved 
(weirdly although...)

Thank you for your help.
```

Original comment by `bernardoopinto@gmail.com` on 7 Feb 2011 at 1:29

**Comment by yawlfoundation** [comment]
```
Great! will close
```

Original comment by `yawl.mic...@gmail.com` on 9 Feb 2011 at 1:35
* Changed state: **ClosedWithoutChange**

**Comment by yawlfoundation** [comment]
```
Yes, Same thing is happening to me and I am not able to solve it by any means. 
I tried with both option of java installation then also it is not working. 
System MAC os x 

my problem is exactly the same
Couldn't connect to datasource - starting with an empty dataset
Please do help me.

```

Original comment by `sajan.o...@gmail.com` on 22 May 2011 at 7:10

Attachments:
* [Screen shot 2011-05-22 at 8.29.38 AM.png](https://storage.googleapis.com/google-code-attachments/yawl/issue-414/comment-4/Screen shot 2011-05-22 at 8.29.38 AM.png)
