### ISSUE TITLE
Cannot save or analyze the specification which was exported be the Oryx editor

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#449]
```
What steps will reproduce the problem?
1. export bpmn 1.2 model as a yawl specification in Oryx editor
2. open the specification in the YAWL editor
3. try to analyze the specification or edit something and try to save.

What is the expected output? What do you see instead?

Analysis result or information that the specification is invalid.


What version of the product are you using? On what operating system?

Windows 7, YAWL 2.1, YAWL 2.2beta

Please provide any additional information below.

Exception from the log file:

2011-08-03 21:19:46,961 [ERROR] :- Error saving specification to file.
java.lang.NullPointerException
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateOfferFilters(EngineSpecificationExporter.java:1174)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateOfferInteractionDetail(EngineSpecificationExporter.java:1116)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateResourceMappingDetail(EngineSpecificationExporter.java:1051)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateResourceDetail(EngineSpecificationExporter.java:1009)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.setAtomicTasks(EngineSpecificationExporter.java:643)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.setElements(EngineSpecificationExporter.java:541)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateEngineNetFrom(EngineSpecificationExporter.java:476)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateEngineNets(EngineSpecificationExporter.java:463)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.getEngineSpecAsEngineObjects(EngineSpecificationExporter.java:256)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.getAndCheckEngineSpecificationXML(EngineSpecificationExporter.java:192)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.checkAndExportEngineSpecToFile(EngineSpecificationExporter.java:95)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.saveSpecificationToFile(EngineSpecificationHandler.java:170)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.engineFormatFileExport(EngineSpecificationHandler.java:87)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.AvailableEngineProxyImplementation.engineFormatFileExport(AvailableEngineProxyImplementation.java:74)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.YAWLEngineProxy.engineFormatFileExport(YAWLEngineProxy.java:92)
	at org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.saveUpdatingGUI(SpecificationArchiveHandler.java:183)
	at org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.saveUpdatingGUI(SpecificationArchiveHandler.java:163)
	at org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.processSaveAsRequest(SpecificationArchiveHandler.java:158)
	at org.yawlfoundation.yawl.editor.specification.ArchivingThread.processRequestState(ArchivingThread.java:138)
	at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run(ArchivingThread.java:115)
2011-08-03 21:20:58,771 [ERROR] :- Error saving specification to file.
java.lang.NullPointerException
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateOfferFilters(EngineSpecificationExporter.java:1174)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateOfferInteractionDetail(EngineSpecificationExporter.java:1116)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateResourceMappingDetail(EngineSpecificationExporter.java:1051)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateResourceDetail(EngineSpecificationExporter.java:1009)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.setAtomicTasks(EngineSpecificationExporter.java:643)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.setElements(EngineSpecificationExporter.java:541)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateEngineNetFrom(EngineSpecificationExporter.java:476)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.populateEngineNets(EngineSpecificationExporter.java:463)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.getEngineSpecAsEngineObjects(EngineSpecificationExporter.java:256)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.getAndCheckEngineSpecificationXML(EngineSpecificationExporter.java:192)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationExporter.checkAndExportEngineSpecToFile(EngineSpecificationExporter.java:95)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.saveSpecificationToFile(EngineSpecificationHandler.java:170)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.EngineSpecificationHandler.engineFormatFileExport(EngineSpecificationHandler.java:87)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.AvailableEngineProxyImplementation.engineFormatFileExport(AvailableEngineProxyImplementation.java:74)
	at org.yawlfoundation.yawl.editor.thirdparty.engine.YAWLEngineProxy.engineFormatFileExport(YAWLEngineProxy.java:92)
	at org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.saveUpdatingGUI(SpecificationArchiveHandler.java:183)
	at org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.saveUpdatingGUI(SpecificationArchiveHandler.java:163)
	at org.yawlfoundation.yawl.editor.specification.SpecificationArchiveHandler.processSaveRequest(SpecificationArchiveHandler.java:102)
	at org.yawlfoundation.yawl.editor.specification.ArchivingThread.processRequestState(ArchivingThread.java:134)
	at org.yawlfoundation.yawl.editor.specification.ArchivingThread.run(ArchivingThread.java:115)


```

Original issue reported on code.google.com by `phob...@gmail.com` on 3 Aug 2011 at 7:31

Attachments:
* [OryxBPMNToYAWL_0.yawl](https://storage.googleapis.com/google-code-attachments/yawl/issue-449/comment-0/OryxBPMNToYAWL_0.yawl)

**Comment by yawlfoundation** [comment]
```
The xml output by Oryx is incorrect, specifically the 'resourcing' section of 
the task definition. When 
    
    <offer initiator="system" /> 

child element data is expected to describe how the system should manage the 
offer. If you set the element to 
    
    <offer initiator="user" />

the yawl editor will handle is successfully. 
```

Original comment by `yawl.mic...@gmail.com` on 5 Aug 2011 at 12:43
* Changed state: **ClosedWithoutChange**
