### ISSUE TITLE
YAWL Engine start causes Database connection errors

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#545]
```
I installed YAWL 3.0 using the YAWL-3.0-linux-x64-installer.run installer.

I'm running on x64 linux with 512MB of main memory and a swap of 4GB.
The server running this is dedicated to running YAWL, no other services are 
running.

When I start Tomcat using bin/startup.sh, I get a lot of database-related 
exceptions in logs/catalina.out, the first of which is shown below:

INFO: Deploying web application directory 
/root/YAWL-3.0/engine/apache-tomcat-7.0.55/webapps/yawl
ERROR - HHH000319: Could not get database metadata
java.sql.SQLException: Connections could not be acquired from the underlying 
database!
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
        at org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider.getConnection(C3P0ConnectionProvider.java:84)
        at org.hibernate.tool.hbm2ddl.ManagedProviderConnectionHelper.prepare(ManagedProviderConnectionHelper.java:55)
        at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:194)
        at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:178)
        at org.yawlfoundation.yawl.engine.YPersistenceManager.initialise(YPersistenceManager.java:94)
        at org.yawlfoundation.yawl.engine.YEngine.getInstance(YEngine.java:150)
        at org.yawlfoundation.yawl.engine.interfce.EngineGatewayImpl.<init>(EngineGatewayImpl.java:92)
        at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EngineBasedServer.init(InterfaceB_EngineBasedServer.java:82)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5229)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5516)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1898)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A 
ResourcePool could not acquire a resource from its primary factory or source.
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
        ... 26 more

After a while, the engine does start, and I'm able to load the login screen.
However, when I log in, I get a NullPointerException in 
org.yawlfoundation.yawl.resourcing.InterfaceClients.connected(InterfaceClients.j
ava:258)
```

Original issue reported on code.google.com by `TimMarco...@gmail.com` on 23 Mar 2015 at 5:17

**Comment by yawlfoundation** [comment]
```
Can you please try updating the c3p0 library: copy the attached file 
(c3p0-0.9.5.jar) to /root/YAWL-3.0/engine/apache-tomcat-7.0.55/yawllib, rename 
the existing c3p0-0.9.1.jar to c3p0-0.9.1.jar.old, and restart yawl.

Please advise if this helps. Thanks 
```

Original comment by `yawl.mic...@gmail.com` on 24 Mar 2015 at 12:21
* Changed state: **Started**

Attachments:
* [c3p0-0.9.5.jar](https://storage.googleapis.com/google-code-attachments/yawl/issue-545/comment-1/c3p0-0.9.5.jar)

**Comment by yawlfoundation** [comment]
```
The server does seem to start correctly, however, when I try to load the 
resourceService, I get the following exception.
I double-checked the permissions for c3p0-0.9.5.jar, it should be getting 
loaded.

Exception Details: java.lang.NoClassDefFoundError 
  Could not initialize class com.mchange.v2.c3p0.DataSources

Possible Source of Error: 
   Class Name: org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider 
   File Name: C3P0ConnectionProvider.java 
   Method Name: configure 
   Line Number: 197 

```

Original comment by `TimMarco...@gmail.com` on 24 Mar 2015 at 11:06

**Comment by yawlfoundation** [comment]
```
Apparently, you may also need the attached mchange-commons library. Try copying 
it to the yawllib dir and restarting. 

Please advise if this resolves the problem.
```

Original comment by `yawl.mic...@gmail.com` on 31 Mar 2015 at 7:30

Attachments:
* [mchange-commons-java-0.2.9.jar](https://storage.googleapis.com/google-code-attachments/yawl/issue-545/comment-3/mchange-commons-java-0.2.9.jar)

**Comment by yawlfoundation** [comment]
```
I still get a lot of database related exceptions in catalina.out:

INFO: Deploying web application directory 
/root/YAWL-3.0/engine/apache-tomcat-7.0.55/webapps/yawl
ERROR - HHH000319: Could not get database metadata
java.sql.SQLException: Connections could not be acquired from the underlying 
database!
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:690)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
        at org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider.getConnection(C3P0ConnectionProvider.java:84)
        at org.hibernate.tool.hbm2ddl.ManagedProviderConnectionHelper.prepare(ManagedProviderConnectionHelper.java:55)
        at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:194)
        at org.hibernate.tool.hbm2ddl.SchemaUpdate.execute(SchemaUpdate.java:178)
        at org.yawlfoundation.yawl.engine.YPersistenceManager.initialise(YPersistenceManager.java:94)
        at org.yawlfoundation.yawl.engine.YEngine.getInstance(YEngine.java:150)
        at org.yawlfoundation.yawl.engine.interfce.EngineGatewayImpl.<init>(EngineGatewayImpl.java:92)
        at org.yawlfoundation.yawl.engine.interfce.interfaceB.InterfaceB_EngineBasedServer.init(InterfaceB_EngineBasedServer.java:82)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5229)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5516)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1247)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1898)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A 
ResourcePool could not acquire a resource from its primary factory or source.
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1463)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:639)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:549)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:756)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:683)
        ... 26 more

And a NullPointerException when logging in:

Exception Details: java.lang.NullPointerException 
  null

Possible Source of Error: 
   Class Name: org.yawlfoundation.yawl.resourcing.InterfaceClients 
   File Name: InterfaceClients.java 
   Method Name: connected 
   Line Number: 258 

```

Original comment by `TimMarco...@gmail.com` on 31 Mar 2015 at 7:11

**Comment by yawlfoundation** [comment]
```
Can you please look in /root/YAWL-3.0/engine/apache-tomcat-7.0.55/database to 
see if it has any content? A database is created there on first startup, and so 
that dir needs full read/write access.
```

Original comment by `yawl.mic...@gmail.com` on 31 Mar 2015 at 11:14

**Comment by yawlfoundation** [comment]
```
it appears this was a permissions problem. the 3.0.1 installer now comes with 
an empty db with the correct permissions preset, which will prevent this 
problem from reoccurring 
```

Original comment by `yawl.mic...@gmail.com` on 1 May 2015 at 12:58
* Changed state: **Fixed**
