### ISSUE TITLE
Issue with the data mapping from a parent-specification to a worklet specification (value not displayed)

### ISSUE THREAD

**Issue by yawlfoundation** [yawlfoundation/yawl#547]
```
What steps will reproduce the problem?
1. Create parent specification with an Input&output net variable (type
string). And create a worklet specification.
2. Map this variable as Input of a task (in the parent specification),
which has an associated worklet
3. Define the variable as Input in the worklet-net and in one of the tasks
of the worklet-spec. (properly mapped)
4. Launch case (parent-specification)

What is the expected output? What do you see instead?
When executing the parent-specification, the case runs OK, and the worklet
is executed OK also; but when arriving into the worklet-task with the
variable defined as input, the Control_Centre displays the box of the
variable, but NOT ITS VALUE. (the value has been typed for a user in one of
the tasks of the top-level specification)
Conclusion: the value of the variable doesn't pass from the parent-spec. to
the worklet-spec. in spite of having the proper mapping defined.
(on the contrary, the mapping-back of a variable updated in the worklet and
displayed later in the parent-spec. gives no problems)

What version of the product are you using? On what operating system?
YAWL4Study 2.0 RC1  ; Windows

Please provide any additional information below.
In the attached files, 
 - TR is the top-level spec.
 - w1 is the worklet spec.
 - PatientID is the varable that should be displayed in the first worklet task

LOG:
17-jun-2009 15:46:16 org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() para servlet InterfaceX_Servlet lanz� excepci�n
java.lang.NumberFormatException: For input string: "announceEngineInitialised"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at
org.yawlfoundation.yawl.engine.interfce.interfaceX.InterfaceX_ServiceSideServer.
processPostQuery(InterfaceX_ServiceSideServer.java:105)
    at
org.yawlfoundation.yawl.engine.interfce.interfaceX.InterfaceX_ServiceSideServer.
doPost(InterfaceX_ServiceSideServer.java:80)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)...
```
Original issue reported on code.google.com by ipongilu...@gmail.com on 17 Jun 2009 at 2:51

Attachments:

    TR.yawl
    w1.yawl
    TR.xrs

**Comment by yawlfoundation** [comment]
```
The problem is the worklet's specification id: 'w1.yawl'. It should exactly 
match the
name of the worklet *without* the file extension, i.e. 'w1'. Take the extension 
off
the specification id and it will work fine.
```
Original comment by yawl.mic...@gmail.com on 18 Jun 2009 at 9:39

    Changed state: ClosedWithoutChange

**Comment by yawlfoundation** [comment]
```
oh, and the NumberFormatException had nothing to do with it. But it did reveal
another obscure bug that is now fixed. 
```
Original comment by yawl.mic...@gmail.com on 18 Jun 2009 at 9:52
